export const MICROSOFT_RSVP_USER = 'test@outlook.com';

export const getMicrosoftRsvpICS = (externalID: string) => `BEGIN:VCALENDAR
METHOD:REPLY
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:tzone://Microsoft/Utc
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;PARTSTAT=ACCEPTED;CN=skiff skiff:mailto:${MICROSOFT_RSVP_USER}
COMMENT;LANGUAGE=en-US:\n
RRULE:FREQ=DAILY;COUNT=10;INTERVAL=1
UID:${externalID}
RECURRENCE-ID;TZID="tzone://Microsoft/Utc":20230221T120000
SUMMARY;LANGUAGE=en-US:Accepted: Test Microsft
DTSTART;TZID="tzone://Microsoft/Utc":20230221T120000
DTEND;TZID="tzone://Microsoft/Utc":20230221T123000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20230219T140000Z
TRANSP:OPAQUE
STATUS:DECLINED
SEQUENCE:0
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
`;
